# https://medium.com/geekculture/deploy-to-google-app-engine-using-github-actions-ci-cd-f25d4c965fbc

name: GAE

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    permissions:
     contents: 'read'
     id-token: 'write'
     
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    
    steps:
    # actions/checkout MUST come before auth
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{secrets.CREDENTIALS_JSON}}'
        
#    - name: Checkout
#      uses: actions/checkout@v2

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: appengine/dispatch.yaml appengine/testing/app.yaml appengine/default/app.yaml
        version: v1
        project_id: ${{ secrets.PROJECT_ID }}
        credentials: ${{ secrets.CREDENTIALS_JSON }}

    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}"
